ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_account_holder VARCHAR(255);
